import { Question } from "../InterviewSubjects";

// Collection of 60 most asked puzzle questions in interviews
export const puzzleQuestions: Question[] = [
  // Logical Puzzles
  {
    id: "puzzle-1",
    question: "Pay an employee using a gold rod of 7 units - You have a gold rod of 7 units and need to pay an employee 1 unit per day for 7 days. You can only make 2 cuts. How do you do it?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Cut the rod into pieces of 1, 2, and 4 units. Day 1: Give 1 unit. Day 2: Give 2 units, take back 1 unit. Day 3: Give back 1 unit (now has 1+2=3). Day 4: Give 4 units, take back 1+2 units. Day 5: Give 1 unit (now has 4+1=5). Day 6: Give 2 units, take back 1 unit (now has 4+2=6). Day 7: Give 1 unit (now has 4+2+1=7). The key insight is using binary representation and making strategic exchanges.",
    tips: [
      "Think about binary representation of numbers",
      "Consider making exchanges, not just giving",
      "Use powers of 2: 1, 2, 4",
      "Practice with the exchange sequence"
    ],
    tags: ["logical", "binary", "exchange", "strategy"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-2",
    question: "Find the fastest 3 horses - You have 25 horses and can race 5 at a time. What's the minimum number of races needed to find the 3 fastest horses?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 7 races. Step 1: Race all 25 horses in 5 groups (5 races). Step 2: Race the winners of each group (1 race). Step 3: The winner of race 6 is the fastest horse overall. For 2nd and 3rd fastest, they must come from the groups whose winners finished 1st, 2nd, or 3rd in race 6. Race the 2nd and 3rd horses from the winning group, the 2nd horse from the 2nd group, and the winner of the 3rd group (1 race). The top 2 from this race are the 2nd and 3rd fastest overall.",
    tips: [
      "Eliminate horses systematically",
      "The fastest is easy - winner of winners",
      "2nd and 3rd must be from top groups only",
      "Draw a diagram to visualize possibilities"
    ],
    tags: ["logical", "elimination", "optimization", "racing"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-3",
    question: "3 Bulbs and 3 Switches - You have 3 light bulbs in one room and 3 switches in another room. You can only visit the bulb room once. How do you determine which switch controls which bulb?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Turn on the first switch for a few minutes, then turn it off. Turn on the second switch and leave it on. Leave the third switch off. Go to the bulb room. The bulb that is ON is controlled by the second switch. Touch the other two bulbs - the one that is warm (but off) is controlled by the first switch, and the cool one is controlled by the third switch. This uses the fact that incandescent bulbs generate heat.",
    tips: [
      "Think beyond just on/off states",
      "Use heat as an additional property",
      "Time is a factor - let bulbs heat up",
      "This assumes incandescent bulbs, not LED"
    ],
    tags: ["logical", "heat", "states", "observation"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-4",
    question: "100 Prisoners with Red/Black Hats - 100 prisoners stand in a line, each wearing either a red or black hat. Each can see all hats in front but not their own or behind. Starting from the back, each must say 'red' or 'black'. How can they maximize survivors?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "The last prisoner (who can see all 99 others) counts the number of red hats visible and says 'red' if the count is odd, 'black' if even. This establishes a parity system. Each subsequent prisoner can deduce their hat color by comparing the established parity with what they see and what previous prisoners said. This strategy guarantees 99 prisoners survive, with the first prisoner having a 50% chance.",
    tips: [
      "Use the first prisoner to establish information",
      "Think about parity (odd/even) as information",
      "Each prisoner uses cumulative information",
      "Strategy guarantees maximum possible survivors"
    ],
    tags: ["logical", "parity", "information", "strategy"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-5",
    question: "Camel and Banana Puzzle - A camel needs to transport 3000 bananas across a 1000km desert. The camel can carry 1000 bananas at a time but eats 1 banana per km. What's the maximum bananas that can be transported?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 833 bananas. Strategy: Create intermediate dumps. Phase 1 (0-200km): Make 5 trips to transport all 3000 bananas 200km forward, consuming 3000 bananas total, leaving 2000 at the 200km mark. Phase 2 (200-600km): Make 3 trips to transport 2000 bananas 400km forward, consuming 1200 bananas, leaving 1000 at 600km mark. Phase 3 (600-1000km): Single trip for remaining 400km, consuming 400 bananas, arriving with 533 bananas. Wait, recalculating: 1000 - 167 = 833 bananas arrive.",
    tips: [
      "Create intermediate storage points",
      "Minimize total distance traveled",
      "Calculate optimal switch points",
      "Work backwards from the destination"
    ],
    tags: ["logical", "optimization", "resource-management", "strategy"],
    estimatedTime: 8,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-6",
    question: "Find the Jar with contaminated pills - You have 10 jars of pills. 9 jars contain pills weighing 10g each, 1 jar contains contaminated pills weighing 11g each. You have a scale that can measure exact weight. What's the minimum number of weighings needed?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 1 weighing. Number the jars 1-10. Take 1 pill from jar 1, 2 pills from jar 2, 3 pills from jar 3, ..., 10 pills from jar 10. If all pills were normal (10g each), total weight would be (1+2+...+10) × 10 = 550g. The actual weight will be 550 + n grams, where n is the jar number containing contaminated pills. For example, if the weight is 557g, then jar 7 contains the contaminated pills.",
    tips: [
      "Use different quantities from each jar",
      "Create a unique signature for each jar",
      "The excess weight directly identifies the jar",
      "This is more efficient than binary search"
    ],
    tags: ["logical", "weighing", "identification", "optimization"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-7",
    question: "10 Coins Puzzle - You have 10 coins, some are heads up and some are tails up. You are blindfolded and can't feel which side is up. How do you separate them into two groups with equal numbers of heads?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Let's say there are H heads initially. Divide the coins into two groups: one with X coins and another with (10-X) coins. Flip all coins in the first group. If the first group originally had h heads, after flipping it will have (X-h) heads. For equal heads in both groups: (X-h) = (H-h), which gives us X = H. So divide coins into groups of H and (10-H) coins, then flip all coins in the H-coin group. Both groups will have equal heads.",
    tips: [
      "Think about the effect of flipping coins",
      "Use algebra to represent the problem",
      "The initial number of heads determines group size",
      "Flipping changes heads to tails and vice versa"
    ],
    tags: ["logical", "coins", "flipping", "equal-distribution"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-8",
    question: "Strategy for a 2-Player Coin Game - Two players take turns removing 1, 2, or 3 coins from a pile of 20 coins. The player who takes the last coin wins. What's the winning strategy?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "The winning strategy is to always leave your opponent with a multiple of 4 coins. Since players can take 1, 2, or 3 coins, whatever they take, you can take enough to make the total taken in that round equal to 4. Starting with 20 coins (multiple of 4), the second player has the winning strategy. If the first player takes X coins (1, 2, or 3), the second player should take (4-X) coins, always leaving a multiple of 4 for the first player.",
    tips: [
      "Look for patterns in winning/losing positions",
      "Work backwards from the end condition",
      "Identify the key invariant (multiples of 4)",
      "Control the game by maintaining the invariant"
    ],
    tags: ["logical", "game-theory", "strategy", "invariant"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-9",
    question: "5 Pirates and 100 Gold Coins - 5 pirates have 100 gold coins to distribute. They vote in order of seniority. If the proposal gets majority support, it's accepted; otherwise, the proposer is thrown overboard. Pirates are rational and greedy. What should the senior pirate propose?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Senior pirate should propose: 98 for himself, 0 for pirate 2, 1 for pirate 3, 0 for pirate 4, 1 for pirate 5. Reasoning: Work backwards. If only pirates 4 and 5 remain, pirate 4 takes all 100 coins. If pirates 3, 4, 5 remain, pirate 3 needs pirate 5's vote, so offers 1 to pirate 5 (pirate 5 prefers 1 over 0). With pirates 2, 3, 4, 5, pirate 2 needs 2 votes; offers 1 to pirate 4 and 1 to pirate 3. With all 5 pirates, senior needs 3 votes total (including his own), so he needs 2 more votes. He offers 1 to pirates 3 and 5 (who would get nothing if pirate 2 makes the proposal).",
    tips: [
      "Work backwards from the simplest case",
      "Each pirate wants to maximize their gain",
      "Consider what happens if current proposal fails",
      "Minimum bribe needed to secure votes"
    ],
    tags: ["logical", "game-theory", "backwards-induction", "rational-choice"],
    estimatedTime: 8,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-10",
    question: "Minimum Cut Puzzle - You have a 3x3 chocolate bar. What's the minimum number of cuts needed to separate it into 9 individual pieces?",
    category: "logical",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: 8 cuts. Each cut increases the number of pieces by exactly 1. Starting with 1 piece (the whole bar), to get 9 pieces, you need exactly 8 cuts. This is true regardless of how you make the cuts - whether you stack pieces or cut them individually. The key insight is that each cut operation can only increase the piece count by 1, so to go from 1 piece to 9 pieces requires exactly 8 cuts.",
    tips: [
      "Each cut increases piece count by exactly 1",
      "Total pieces = 1 + number of cuts",
      "Stacking doesn't change this fundamental rule",
      "This applies to any rectangle divided into unit squares"
    ],
    tags: ["logical", "cutting", "invariant", "counting"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Mathematical Puzzles
  {
    id: "puzzle-11",
    question: "Clock Angle Problem - What is the angle between hour and minute hands at 3:15?",
    category: "mathematical",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "At 3:15: Minute hand is at 15 minutes = 15 × 6° = 90° from 12 o'clock. Hour hand moves 30° per hour + 0.5° per minute. At 3:15, hour hand is at 3 × 30° + 15 × 0.5° = 90° + 7.5° = 97.5° from 12 o'clock. The angle between them is |97.5° - 90°| = 7.5°.",
    tips: [
      "Minute hand moves 6° per minute",
      "Hour hand moves 30° per hour or 0.5° per minute",
      "Calculate both positions from 12 o'clock",
      "Take the smaller of the two possible angles"
    ],
    tags: ["mathematical", "clock", "angles", "time"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-12",
    question: "Water Jug Problem - You have two jugs: one 5-liter and one 3-liter. How do you measure exactly 4 liters?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Solution: 1) Fill the 5L jug completely. 2) Pour from 5L jug into 3L jug (5L jug now has 2L, 3L jug is full). 3) Empty the 3L jug. 4) Pour the 2L from the 5L jug into the 3L jug. 5) Fill the 5L jug again. 6) Pour from 5L jug into 3L jug until it's full (this adds 1L to the 3L jug, leaving exactly 4L in the 5L jug).",
    tips: [
      "Use one jug to measure remainder in the other",
      "Think about what remainders you can create",
      "Multiple solutions may exist",
      "This relates to the GCD of the jug sizes"
    ],
    tags: ["mathematical", "measurement", "water-jug", "gcd"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-13",
    question: "Handshake Problem - In a party of 20 people, everyone shakes hands with everyone else exactly once. How many handshakes occur?",
    category: "mathematical",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "This is a combination problem. We need to choose 2 people from 20 for each handshake. Using combinations: C(20,2) = 20!/(2!(20-2)!) = (20 × 19)/2 = 190 handshakes. Alternatively, think of it as: first person shakes hands with 19 others, second person with 18 remaining others (already shook with first), third with 17 remaining, etc. Total = 19 + 18 + 17 + ... + 1 = 19 × 20/2 = 190.",
    tips: [
      "This is choosing 2 people from n people",
      "Formula: n(n-1)/2",
      "Each handshake involves exactly 2 people",
      "Don't double count - A shaking with B is same as B shaking with A"
    ],
    tags: ["mathematical", "combinations", "counting", "handshakes"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-14",
    question: "Age Puzzle - A father is 4 times as old as his son. In 20 years, he will be twice as old as his son. How old are they now?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Let son's current age = x, father's current age = 4x. In 20 years: son will be (x + 20), father will be (4x + 20). Given: 4x + 20 = 2(x + 20). Solving: 4x + 20 = 2x + 40, so 2x = 20, therefore x = 10. Current ages: Son is 10 years old, Father is 40 years old. Verification: Father is 4 times son's age (40 = 4×10 ✓). In 20 years: Son will be 30, Father will be 60, and 60 = 2×30 ✓.",
    tips: [
      "Set up variables for current ages",
      "Write equations for both current and future conditions",
      "Solve the system of equations",
      "Always verify your answer"
    ],
    tags: ["mathematical", "algebra", "age-problems", "equations"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-15",
    question: "Bridge Crossing Problem - 4 people need to cross a bridge at night with one flashlight. Bridge holds 2 people max. Crossing times: A=1min, B=2min, C=5min, D=10min. What's the minimum time?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Minimum time: 17 minutes. Strategy: 1) A and B cross together (2 min). 2) A returns with flashlight (1 min). 3) C and D cross together (10 min). 4) B returns with flashlight (2 min). 5) A and B cross together again (2 min). Total: 2+1+10+2+2 = 17 minutes. The key insight is to have the two fastest people facilitate the crossing of the two slowest people, rather than having the fastest person shuttle everyone across individually.",
    tips: [
      "Compare shuttle strategy vs. fast-pair strategy",
      "Send fastest two first, then slowest two",
      "Minimize the impact of slow crossers",
      "Calculate both strategies and choose minimum"
    ],
    tags: ["mathematical", "optimization", "bridge-crossing", "strategy"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Pattern Recognition Puzzles
  {
    id: "puzzle-16",
    question: "Number Sequence - What's the next number in the sequence: 1, 1, 2, 3, 5, 8, 13, ?",
    category: "pattern",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: 21. This is the Fibonacci sequence where each number is the sum of the two preceding numbers. 1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13, 8+13=21. The Fibonacci sequence appears frequently in nature and mathematics, with applications in computer science algorithms, financial markets, and art.",
    tips: [
      "Look for arithmetic or geometric progressions first",
      "Check if each term relates to previous terms",
      "Fibonacci is sum of two previous terms",
      "Consider differences between consecutive terms"
    ],
    tags: ["pattern", "fibonacci", "sequence", "mathematics"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-17",
    question: "Missing Number Pattern - Find the missing number: 2, 6, 12, 20, 30, ?, 56",
    category: "pattern",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 42. The pattern is n(n+1) where n starts from 2. 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42, 7×8=56. Alternatively, look at differences: 6-2=4, 12-6=6, 20-12=8, 30-20=10. The differences form an arithmetic sequence increasing by 2 each time, so next difference is 12, making the missing number 30+12=42.",
    tips: [
      "Look at differences between consecutive terms",
      "Check if differences form a pattern",
      "Consider products of consecutive integers",
      "Try expressing terms as formulas with n"
    ],
    tags: ["pattern", "arithmetic", "differences", "formulas"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-18",
    question: "Letter Pattern - What comes next: A, D, G, J, M, ?",
    category: "pattern",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: P. Each letter is 3 positions ahead in the alphabet. A(1) + 3 = D(4), D(4) + 3 = G(7), G(7) + 3 = J(10), J(10) + 3 = M(13), M(13) + 3 = P(16). This is an arithmetic sequence with common difference of 3 in terms of alphabetical positions.",
    tips: [
      "Convert letters to numbers (A=1, B=2, etc.)",
      "Look for arithmetic patterns in the numbers",
      "Check differences between positions",
      "Convert back to letters for the answer"
    ],
    tags: ["pattern", "alphabet", "arithmetic", "sequence"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Logic Grid Puzzles
  {
    id: "puzzle-19",
    question: "Einstein's Riddle (Simplified) - There are 5 houses in different colors. The green house is directly to the right of the ivory house. The red house is in the middle. What's the order of houses?",
    category: "logic-grid",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Given constraints: Red house is in middle (position 3), Green house is directly to the right of Ivory house. Since Green is directly right of Ivory, possible positions are: Ivory-Green in positions (1,2), (2,3), (3,4), or (4,5). Since Red is in position 3, Ivory-Green cannot be in (2,3). If Ivory-Green are in (1,2), then positions are: Ivory, Green, Red, ?, ?. If in (3,4), then Red can't be in position 3. If in (4,5), then positions are: ?, ?, Red, Ivory, Green. Need more constraints to determine unique solution.",
    tips: [
      "Use process of elimination systematically",
      "Create a grid to track possibilities",
      "Use constraints to eliminate impossible combinations",
      "Work through logical deductions step by step"
    ],
    tags: ["logic-grid", "deduction", "constraints", "elimination"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-20",
    question: "Truth Teller and Liar - You meet two people. One always tells the truth, one always lies. You can ask one yes/no question to determine which is which. What do you ask?",
    category: "logic-grid",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Ask either person: 'Would the other person say that you are the truth-teller?' If you ask the truth-teller, they know the liar would say 'No' (lie), so the truth-teller answers 'No'. If you ask the liar, they know the truth-teller would say 'No' (truth), but the liar lies, so answers 'Yes'. Therefore, whoever answers 'No' is the truth-teller, and whoever answers 'Yes' is the liar.",
    tips: [
      "Consider what each type would say about the other",
      "Use nested logic - what would X say about Y",
      "The truth-teller reports lies accurately",
      "The liar inverts what they know the truth-teller would say"
    ],
    tags: ["logic-grid", "truth-liar", "meta-logic", "deduction"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Lateral Thinking Puzzles
  {
    id: "puzzle-21",
    question: "The Man in the Elevator - A man lives on the 20th floor but only takes the elevator to the 10th floor, then walks the rest. On rainy days, he takes the elevator all the way up. Why?",
    category: "lateral-thinking",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "The man is too short to reach the button for the 20th floor. He can only reach up to the 10th floor button. On rainy days, he carries an umbrella which he can use to press the higher buttons. This puzzle tests lateral thinking by requiring you to think beyond the obvious explanations and consider physical limitations.",
    tips: [
      "Think about physical limitations or constraints",
      "Consider what's different about rainy days",
      "Don't assume the obvious explanation",
      "Look for creative, non-obvious solutions"
    ],
    tags: ["lateral-thinking", "physical-constraints", "creative", "assumption"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-22",
    question: "The Barber Paradox - In a town, the barber shaves only those men who do not shave themselves. Who shaves the barber?",
    category: "lateral-thinking",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "This is a famous logical paradox. If the barber shaves himself, then he belongs to the group of men who shave themselves, but he's supposed to only shave men who don't shave themselves. If he doesn't shave himself, then he belongs to the group of men who don't shave themselves, which means he should shave himself. The paradox shows that the initial premise is logically inconsistent - such a barber cannot exist under these rules.",
    tips: [
      "This is a self-reference paradox",
      "Consider both cases: barber shaves self vs. doesn't",
      "Both cases lead to contradictions",
      "The premise itself is logically impossible"
    ],
    tags: ["lateral-thinking", "paradox", "self-reference", "logic"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-23",
    question: "The Chicken and Egg Problem - A chicken and a half lays an egg and a half in a day and a half. How many eggs does one chicken lay in one day?",
    category: "lateral-thinking",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 2/3 of an egg per day. If 1.5 chickens lay 1.5 eggs in 1.5 days, then the rate is (1.5 eggs)/(1.5 chickens × 1.5 days) = 1.5/(2.25) = 2/3 eggs per chicken per day. Alternatively: 1.5 chickens lay 1.5 eggs in 1.5 days, so 1 chicken lays 1 egg in 1.5 days, which means 1 chicken lays 2/3 eggs in 1 day.",
    tips: [
      "Set up the rate equation carefully",
      "Don't be confused by fractions of chickens/eggs",
      "Calculate eggs per chicken per day",
      "Work with the ratios systematically"
    ],
    tags: ["lateral-thinking", "rates", "fractions", "word-problem"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Probability Puzzles
  {
    id: "puzzle-24",
    question: "Monty Hall Problem - You choose door 1 of 3 doors (one has a car, two have goats). Host opens door 3 showing a goat. Should you switch to door 2?",
    category: "probability",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Yes, you should switch. Initially, each door has 1/3 probability of having the car. When you choose door 1, it has 1/3 probability, and doors 2&3 together have 2/3 probability. When the host opens door 3 (showing a goat), the 2/3 probability doesn't disappear - it transfers entirely to door 2. So door 1 still has 1/3 probability, but door 2 now has 2/3 probability. Switching doubles your chances of winning.",
    tips: [
      "The host's action provides information",
      "Initial probabilities don't change for your door",
      "The 2/3 probability concentrates on the remaining door",
      "Think about what the host knows vs. what you know"
    ],
    tags: ["probability", "monty-hall", "conditional", "counterintuitive"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-25",
    question: "Birthday Paradox - In a group of 23 people, what's the probability that at least two people share the same birthday?",
    category: "probability",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: Approximately 50.7%. It's easier to calculate the probability that all have different birthdays, then subtract from 1. P(all different) = (365/365) × (364/365) × (363/365) × ... × (343/365) ≈ 0.493. Therefore, P(at least one match) = 1 - 0.493 = 0.507 or about 50.7%. This seems counterintuitive because we're not asking for a specific birthday match, but any match among all possible pairs.",
    tips: [
      "Calculate complement: probability all different",
      "Each person must have different birthday from all previous",
      "There are C(23,2) = 253 possible pairs",
      "This is counterintuitive but mathematically correct"
    ],
    tags: ["probability", "birthday-paradox", "complement", "counterintuitive"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-26",
    question: "Two Envelope Problem - You have two envelopes, one contains twice as much money as the other. You pick one and see $100. Should you switch?",
    category: "probability",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "This is a famous paradox. The naive analysis suggests always switching: if you have $100, the other envelope has either $50 or $200 with equal probability, giving expected value of $125. However, this reasoning is flawed because it assumes equal probability regardless of the amount observed. The correct analysis depends on the prior distribution of money amounts. Without knowing this distribution, you cannot determine whether switching is beneficial.",
    tips: [
      "The naive expected value calculation is misleading",
      "The problem depends on prior probability distributions",
      "Equal probability assumption may not be valid",
      "This highlights issues with infinite expected values"
    ],
    tags: ["probability", "paradox", "expected-value", "prior-distribution"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // River Crossing Puzzles
  {
    id: "puzzle-27",
    question: "Fox, Chicken, and Grain - A farmer needs to cross a river with a fox, chicken, and grain. The boat holds only the farmer plus one item. Fox can't be alone with chicken, chicken can't be alone with grain. How to cross?",
    category: "river-crossing",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Solution: 1) Farmer takes chicken across. 2) Farmer returns alone. 3) Farmer takes fox across, brings chicken back. 4) Farmer leaves chicken, takes grain across. 5) Farmer returns alone. 6) Farmer takes chicken across. The key insight is step 3: bring the chicken back to prevent it from being alone with the grain while the fox is on the other side.",
    tips: [
      "Sometimes you need to bring items back",
      "Identify which pairs cannot be left alone",
      "The chicken is the most restrictive item",
      "Work through each step carefully"
    ],
    tags: ["river-crossing", "constraints", "backtracking", "strategy"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-28",
    question: "Family River Crossing - A family of 5 (taking 1, 2, 5, 8, 12 minutes to cross) must cross a bridge at night. Bridge holds 2 people, they need the flashlight, and they must walk at the slower person's pace. What's minimum time?",
    category: "river-crossing",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Minimum time: 29 minutes. Strategy: 1) 1 and 2 cross (2 min). 2) 1 returns (1 min). 3) 8 and 12 cross (12 min). 4) 2 returns (2 min). 5) 1 and 5 cross (5 min). 6) 1 returns (1 min). 7) 1 and 2 cross (2 min). Total: 2+1+12+2+5+1+2 = 29 minutes. The key is to have the fastest person shuttle others while having the two slowest cross together.",
    tips: [
      "Have two slowest people cross together",
      "Use fastest person as shuttle",
      "Minimize impact of slowest crossers",
      "Calculate different strategies and compare"
    ],
    tags: ["river-crossing", "optimization", "time-management", "strategy"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Weighing Puzzles
  {
    id: "puzzle-29",
    question: "12 Balls Problem - You have 12 balls, 11 identical and 1 different (heavier or lighter). Using a balance scale 3 times, identify the different ball and whether it's heavier or lighter.",
    category: "weighing",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "First weighing: Divide into groups of 4-4-4. Weigh group A vs group B. If balanced, different ball is in group C. If unbalanced, different ball is in the heavier or lighter group. Second weighing depends on first result. For example, if A > B, weigh 3 balls from A against 3 known normal balls. If balanced, the different ball is the 4th from A (heavier). If A side is heavier, different ball is among those 3 (heavier). Third weighing identifies the specific ball.",
    tips: [
      "Divide into equal groups for maximum information",
      "Use process of elimination systematically",
      "Track both identity and weight direction",
      "Each weighing should eliminate 2/3 of possibilities"
    ],
    tags: ["weighing", "balance-scale", "elimination", "information"],
    estimatedTime: 8,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-30",
    question: "9 Coins, 1 Fake - You have 9 coins, 8 real and 1 fake (lighter). What's minimum weighings needed to find the fake coin using a balance scale?",
    category: "weighing",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 2 weighings. First weighing: Divide into groups of 3-3-3. Weigh first group vs second group. If balanced, fake is in third group. If unbalanced, fake is in the lighter group. Second weighing: Take the group with the fake coin, weigh 1 coin vs 1 coin. If balanced, the third coin is fake. If unbalanced, the lighter coin is fake. This uses ternary search principle - each weighing eliminates 2/3 of possibilities.",
    tips: [
      "Divide into three equal groups",
      "Each weighing gives three possible outcomes",
      "Use ternary elimination strategy",
      "Two weighings can distinguish among 9 items"
    ],
    tags: ["weighing", "ternary-search", "elimination", "minimum"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // Additional Classic Puzzles
  {
    id: "puzzle-31",
    question: "The Prisoner's Dilemma - Two prisoners are arrested and held separately. Each can either cooperate (stay silent) or defect (betray the other). What's the rational choice?",
    category: "game-theory",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "In the classic one-shot game, the rational choice is to defect. Regardless of what the other prisoner does, defecting gives a better outcome: if the other cooperates, you go free instead of getting a light sentence; if the other defects, you get a heavy sentence instead of the worst sentence. However, this leads to both prisoners defecting and getting a worse outcome than if both had cooperated. This illustrates the conflict between individual rationality and collective benefit.",
    tips: [
      "Analyze each player's best response to opponent's actions",
      "Defection dominates cooperation in one-shot games",
      "The Nash equilibrium may not be Pareto optimal",
      "Repeated games can enable cooperation"
    ],
    tags: ["game-theory", "nash-equilibrium", "cooperation", "rationality"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-32",
    question: "The Traveling Salesman - A salesman must visit 5 cities and return home, visiting each city exactly once. How many possible routes are there?",
    category: "combinatorics",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: 24 routes. Starting from the home city, the salesman has 4 choices for the first city, 3 for the second, 2 for the third, and 1 for the last city before returning home. Total routes = 4! = 4 × 3 × 2 × 1 = 24. If we consider that clockwise and counterclockwise routes are the same (undirected graph), then it's 24/2 = 12 unique routes.",
    tips: [
      "This is a permutation problem",
      "Fix the starting point to avoid counting rotations",
      "Consider if direction matters (directed vs undirected)",
      "For n cities: (n-1)! routes"
    ],
    tags: ["combinatorics", "permutations", "tsp", "factorial"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-33",
    question: "The Muddy Children - 3 children have muddy foreheads. Each can see others but not themselves. A parent says 'at least one of you has mud' and asks who has mud. What happens?",
    category: "logic",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "If all 3 have mud: First round, no one answers (each sees 2 muddy children and thinks they might be the clean one). Second round, everyone realizes that if they were clean, the other two would have figured out they were muddy in round 1. Since they didn't, everyone must be muddy. All three answer simultaneously in round 2. This demonstrates common knowledge vs. mutual knowledge - the parent's statement creates common knowledge.",
    tips: [
      "Each child uses others' lack of response as information",
      "The parent's statement is crucial for common knowledge",
      "Work through different scenarios (1, 2, or 3 muddy)",
      "The delay in response conveys information"
    ],
    tags: ["logic", "common-knowledge", "induction", "information"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-34",
    question: "The Liar's Paradox - Consider the statement: 'This statement is false.' Is it true or false?",
    category: "paradox",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "This creates a logical paradox with no resolution within classical logic. If the statement is true, then what it says must be correct, meaning it's false. If the statement is false, then what it says is incorrect, meaning it's actually true. This paradox highlights limitations of self-referential statements in formal logic systems and has led to important developments in mathematical logic and set theory.",
    tips: [
      "This is a classic self-reference paradox",
      "Both true and false lead to contradictions",
      "Similar to Russell's Paradox in set theory",
      "Shows limitations of naive logical systems"
    ],
    tags: ["paradox", "self-reference", "logic", "contradiction"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-35",
    question: "The Missing Dollar - Three guests pay $30 for a hotel room ($10 each). Manager realizes it should be $25, gives bellboy $5 to return. Bellboy keeps $2, returns $3. Guests paid $27, bellboy has $2. Where's the missing dollar?",
    category: "accounting",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "There's no missing dollar - this is an accounting trick. The guests paid $27 total: $25 to the hotel and $2 to the bellboy. The error is in adding the bellboy's $2 to the guests' $27. The correct accounting is: Guests paid $27 = Hotel received $25 + Bellboy kept $2. The original $30 = Hotel has $25 + Guests got back $3 + Bellboy has $2. The puzzle misleads by suggesting we should add the bellboy's money to what the guests paid.",
    tips: [
      "Track where money actually went",
      "Don't add the bellboy's money to guests' payment",
      "The $2 is part of what guests paid, not additional",
      "Set up proper accounting equations"
    ],
    tags: ["accounting", "misdirection", "arithmetic", "fallacy"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },

  // More Logic Puzzles
  {
    id: "puzzle-36",
    question: "The Hat Color Puzzle - 100 people in a line, each wearing red or blue hat. Each person can see all hats in front. Starting from back, each must guess their hat color. How to maximize correct guesses?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "The person at the back counts red hats visible and says 'red' if odd count, 'blue' if even count. This establishes parity. Each subsequent person can calculate their hat color using the parity information and what they observe. If the parity doesn't match what they see plus previous correct guesses, their hat must be the color that balances it. This guarantees 99 correct guesses minimum.",
    tips: [
      "First person sacrifices themselves to give information",
      "Use parity as a communication method",
      "Each person builds on previous information",
      "Mathematical proof guarantees the strategy"
    ],
    tags: ["logical", "parity", "communication", "optimization"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-37",
    question: "The Poisoned Wine - You have 1000 bottles of wine, one is poisoned. You have 10 test strips that change color if they touch poison. How do you find the poisoned bottle in one test?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Use binary representation. Number bottles 0-999 and convert to 10-bit binary. Each test strip represents one bit position. For each bottle, if bit i is 1, put a drop on test strip i. After testing, the pattern of colored strips gives the binary number of the poisoned bottle. For example, if strips 0, 3, and 7 change color, the poisoned bottle is 2^0 + 2^3 + 2^7 = 1 + 8 + 128 = 137.",
    tips: [
      "Think in terms of binary representation",
      "Each test strip represents one bit",
      "10 bits can represent 2^10 = 1024 values",
      "The pattern of results directly gives the answer"
    ],
    tags: ["logical", "binary", "encoding", "testing"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-38",
    question: "The Wise Men and Hats - Three wise men are told that each has either a red or white hat. Each can see the others' hats but not his own. They're told at least one hat is red. After some time, one wise man correctly declares his hat color. How?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "If a wise man sees two white hats, he immediately knows his is red (since at least one must be red). Since no one immediately speaks, everyone sees at least one red hat. If someone sees one red and one white hat, they reason: 'If my hat were white, the person with the red hat would see two white hats and would have spoken immediately. Since they didn't, my hat must be red.' The person seeing one red hat speaks first.",
    tips: [
      "Use the silence as information",
      "Each person reasons about others' reasoning",
      "The constraint 'at least one red' is crucial",
      "Timing of responses matters"
    ],
    tags: ["logical", "deduction", "meta-reasoning", "constraints"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-39",
    question: "The Burning Ropes - You have two ropes that each burn for exactly 1 hour, but burn unevenly. How do you measure exactly 45 minutes?",
    category: "time",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Light the first rope at both ends and the second rope at one end simultaneously. The first rope will burn completely in 30 minutes (burns from both ends). At that moment, light the other end of the second rope. The second rope will burn for another 15 minutes (it had 30 minutes left, now burning from both ends). Total time: 30 + 15 = 45 minutes.",
    tips: [
      "Burning from both ends halves the time",
      "Use one rope as a timer for the other",
      "Think about when to light the second end",
      "The uneven burning doesn't matter for total time"
    ],
    tags: ["time", "burning", "measurement", "creative"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-40",
    question: "The Water Lily Puzzle - A water lily doubles in size every day. If it takes 30 days to cover the entire pond, on which day does it cover half the pond?",
    category: "exponential",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: Day 29. Since the lily doubles in size every day, on day 29 it covers half the pond, and on day 30 (after doubling) it covers the entire pond. This puzzle tests understanding of exponential growth - many people incorrectly guess day 15 by thinking linearly instead of exponentially.",
    tips: [
      "Think exponentially, not linearly",
      "Work backwards from the final day",
      "Doubling means previous day was half the size",
      "This illustrates exponential growth properties"
    ],
    tags: ["exponential", "growth", "doubling", "backwards"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-41",
    question: "The Airplane Seat Problem - 100 passengers board a plane with 100 seats. The first passenger lost his ticket and sits randomly. Each subsequent passenger sits in their assigned seat if available, otherwise sits randomly. What's the probability the last passenger sits in their own seat?",
    category: "probability",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 50%. Key insight: at any point, only two seats matter - seat 1 (first passenger's) and seat 100 (last passenger's). If anyone sits in seat 1, the chain ends and everyone else sits correctly. If anyone sits in seat 100, the last passenger can't sit there. The process continues until someone sits in either seat 1 or 100. By symmetry, these are equally likely, so probability is 1/2.",
    tips: [
      "Focus on the key seats (first and last)",
      "Intermediate passengers don't affect the final outcome",
      "Use symmetry argument",
      "The chain must end at seat 1 or seat 100"
    ],
    tags: ["probability", "symmetry", "chain-reaction", "invariant"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-42",
    question: "The Chessboard and Wheat - A king promises to give a wise man wheat: 1 grain on first square, 2 on second, 4 on third, doubling each square. How much wheat for all 64 squares?",
    category: "exponential",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 2^64 - 1 grains. This is a geometric series: 1 + 2 + 4 + 8 + ... + 2^63. The sum formula for geometric series is (2^64 - 1)/(2-1) = 2^64 - 1. This equals approximately 18.4 quintillion grains, weighing about 1.2 trillion tons - more wheat than has ever been produced in human history. This illustrates the incredible power of exponential growth.",
    tips: [
      "This is a geometric series with ratio 2",
      "Use the geometric series sum formula",
      "2^64 is approximately 18.4 × 10^18",
      "Put the answer in perspective with real quantities"
    ],
    tags: ["exponential", "geometric-series", "growth", "large-numbers"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-43",
    question: "The Two Doors - You're in front of two doors. One leads to freedom, one to death. Two guards: one always lies, one always tells truth. You can ask one question to one guard. What do you ask?",
    category: "logical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Ask either guard: 'If I asked the other guard which door leads to freedom, what would he say?' Then choose the opposite door. If you ask the truth-teller, he'll honestly report the liar's false answer. If you ask the liar, he'll lie about the truth-teller's honest answer. In both cases, you get the wrong door, so choose the opposite.",
    tips: [
      "Use nested questions to normalize responses",
      "Both guards will point to the wrong door",
      "The double negative gives you the right answer",
      "Alternative: ask about their own door"
    ],
    tags: ["logical", "truth-liar", "nested-logic", "doors"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-44",
    question: "The Hourglass Problem - You have two hourglasses: one measures 7 minutes, one measures 4 minutes. How do you measure exactly 9 minutes?",
    category: "time",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Start both hourglasses simultaneously. When the 4-minute glass runs out, flip it immediately (4 minutes elapsed). When the 7-minute glass runs out, flip the 4-minute glass again (7 minutes elapsed, 4-minute glass has 1 minute of sand in bottom). When the 4-minute glass runs out this second time, exactly 9 minutes have elapsed (7 + 2 = 9, since it only had 1 minute of sand to fall).",
    tips: [
      "Use one timer to create partial measures in the other",
      "Track the state of sand in both glasses",
      "Flipping resets the timer",
      "Combine different timer intervals creatively"
    ],
    tags: ["time", "measurement", "hourglass", "intervals"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-45",
    question: "The Egg Dropping Problem - You have 2 eggs and a 100-story building. What's the minimum number of drops needed to find the highest floor from which an egg won't break?",
    category: "optimization",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 14 drops maximum. Strategy: Start at floor 14. If egg breaks, use second egg to test floors 1-13 linearly (worst case: 13 more drops). If egg doesn't break, go to floor 27 (14+13). Continue with decreasing increments: 14, 27, 39, 50, 60, 69, 77, 84, 90, 95, 99, 100. This ensures that in worst case, you never exceed 14 total drops. The key is using decreasing increments so total drops remain constant regardless of where the critical floor is.",
    tips: [
      "Balance the two phases: finding range vs. linear search",
      "Use decreasing increments to maintain constant worst case",
      "If first egg breaks early, you have more floors to test linearly",
      "This is related to dynamic programming optimization"
    ],
    tags: ["optimization", "dynamic-programming", "eggs", "floors"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-46",
    question: "The Light Switch Problem - There are 100 light switches, all initially off. 100 people walk by: person 1 flips every switch, person 2 flips every 2nd switch, person 3 flips every 3rd switch, etc. Which switches are on at the end?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: Switches 1, 4, 9, 16, 25, 36, 49, 64, 81, 100 (perfect squares). A switch is flipped by person n if the switch number is divisible by n. So switch k is flipped by all divisors of k. A switch ends up ON if it's flipped an odd number of times, which happens when k has an odd number of divisors. Only perfect squares have odd number of divisors because divisors usually come in pairs (d, k/d), except when d = k/d (i.e., d = √k).",
    tips: [
      "Count how many times each switch is flipped",
      "A switch is flipped once for each of its divisors",
      "Only perfect squares have odd number of divisors",
      "Divisors come in pairs except for perfect squares"
    ],
    tags: ["mathematical", "divisors", "perfect-squares", "pattern"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-47",
    question: "The Josephus Problem - 100 people stand in circle, every 2nd person is eliminated. What position should you choose to be the last survivor?",
    category: "mathematical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "For n people and eliminating every 2nd person, use the Josephus formula. For powers of 2, the survivor is always position 1. For other numbers, if n = 2^k + L where L < 2^k, then J(n) = 2L + 1. For 100 people: 100 = 2^6 + 36 = 64 + 36, so L = 36. Therefore J(100) = 2×36 + 1 = 73. The 73rd position (counting from 1) will be the last survivor.",
    tips: [
      "Use the mathematical formula for Josephus problem",
      "Express n as 2^k + L",
      "For elimination step of 2, formula is 2L + 1",
      "Verify with smaller examples first"
    ],
    tags: ["mathematical", "josephus", "elimination", "formula"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-48",
    question: "The Rope Bridge at Night - 4 people with a flashlight must cross a bridge that holds only 2 people. Times: 1, 2, 5, 10 minutes. They must walk at the slower person's pace. What's the minimum time?",
    category: "optimization",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: 17 minutes. Strategy: 1) 1 and 2 cross (2 min). 2) 1 returns (1 min). 3) 5 and 10 cross (10 min). 4) 2 returns (2 min). 5) 1 and 2 cross (2 min). Total: 17 minutes. Alternative strategy of having 1 shuttle everyone would take: 1+10+1+5+1+2 = 20 minutes. The key insight is having the two fastest cross first and last, while the two slowest cross together.",
    tips: [
      "Compare shuttle strategy vs. pairing strategy",
      "Minimize the impact of the slowest people",
      "Have fastest people handle the returns",
      "Calculate both strategies to find minimum"
    ],
    tags: ["optimization", "bridge-crossing", "time-management", "strategy"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-49",
    question: "The Counterfeit Coin - Among 12 coins, one is counterfeit (different weight). Using a balance scale 3 times, find which coin is counterfeit and whether it's heavier or lighter.",
    category: "weighing",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Divide into groups A(1,2,3,4), B(5,6,7,8), C(9,10,11,12). First weighing: A vs B. If balanced, counterfeit is in C. If A>B, counterfeit is in A(heavy) or B(light). Second weighing depends on first result. For A>B case: weigh (1,2,5) vs (3,6,9). This isolates possibilities further. Third weighing identifies the specific coin and its weight. The strategy uses ternary logic - each weighing has 3 outcomes, and 3^3 = 27 > 24 possibilities (12 coins × 2 weight directions).",
    tips: [
      "Use ternary elimination strategy",
      "Each weighing should divide remaining possibilities by 3",
      "Track both coin identity and weight direction",
      "Design weighings to maximize information gain"
    ],
    tags: ["weighing", "ternary", "elimination", "information-theory"],
    estimatedTime: 8,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-50",
    question: "The 25 Horses Racing - You have 25 horses and can race 5 at a time. Find the minimum races needed to determine the top 3 fastest horses overall.",
    category: "optimization",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 7 races. Races 1-5: Race all horses in 5 groups. Race 6: Race the 5 group winners to find the overall fastest. Race 7: The overall fastest is determined. For 2nd and 3rd place, candidates are: 2nd and 3rd from the winning group, 2nd from the group whose winner came 2nd overall, and the winner from the group whose winner came 3rd overall. Race these 5 candidates - the top 2 are the overall 2nd and 3rd fastest.",
    tips: [
      "Eliminate horses that can't be in top 3",
      "The fastest is the winner of winners",
      "Only certain horses can be 2nd or 3rd fastest",
      "Use elimination logic systematically"
    ],
    tags: ["optimization", "elimination", "racing", "ranking"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-51",
    question: "The Prisoners and Light Bulb - 100 prisoners, one light bulb in a room. Each prisoner visits randomly and can toggle the bulb. How can one prisoner correctly announce when all have visited?",
    category: "logical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Designate one prisoner as the 'counter' and one as the 'leader'. Protocol: Non-counter prisoners turn ON the bulb exactly once when they first see it OFF (and never touch it again). The counter turns OFF the bulb whenever he sees it ON and increments his count. When the counter has turned off the bulb 99 times, he announces that all have visited. The leader announces when the counter reports 99. This ensures exactly one signal per prisoner.",
    tips: [
      "Designate specific roles for prisoners",
      "Each prisoner signals exactly once",
      "The counter accumulates all signals",
      "Initial bulb state affects the strategy"
    ],
    tags: ["logical", "counting", "signaling", "protocol"],
    estimatedTime: 6,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-52",
    question: "The Calendar Cube Puzzle - Design two cubes so that you can display any date from 01 to 31 by placing them side by side. What numbers go on each cube?",
    category: "design",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Cube 1: 0, 1, 2, 3, 4, 5. Cube 2: 0, 1, 2, 6, 7, 8. Key insight: 6 and 9 are the same when rotated, so one face can represent both. This allows displaying all dates: 01-09 (using 0 from cube 1), 10-15 (using 1 from cube 1), 20-25 (using 2 from cube 1), etc. The shared 6/9 face is crucial for covering dates like 06, 09, 16, 19, 26, 29.",
    tips: [
      "6 and 9 can be the same face when rotated",
      "Need to cover all digits 0-9 across both cubes",
      "Some digits must appear on both cubes",
      "Work through all 31 dates systematically"
    ],
    tags: ["design", "cubes", "calendar", "rotation"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-53",
    question: "The Boat and Ladder - A boat has a ladder with 10 rungs. Each rung is 1 foot apart. At low tide, 6 rungs are underwater. The tide rises at 6 inches per hour. How many rungs will be underwater after 4 hours?",
    category: "lateral-thinking",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: Still 6 rungs. The boat floats on the water, so as the tide rises, the boat rises with it. The relative position of the ladder to the water surface doesn't change. This puzzle tests whether you consider that floating objects rise with the water level.",
    tips: [
      "Consider that the boat floats",
      "Rising tide lifts the boat",
      "Relative position stays the same",
      "Don't overthink - the obvious trap is the answer"
    ],
    tags: ["lateral-thinking", "floating", "relative-position", "tide"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-54",
    question: "The Monkeys and Coconuts - 5 sailors collect coconuts. During the night, each sailor secretly takes 1/5 of the pile (giving 1 to a monkey when the division isn't exact). In the morning, they divide the remaining pile equally (again giving 1 to monkey). How many coconuts originally?",
    category: "mathematical",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 3121 coconuts originally. Work backwards: if N coconuts remain for morning division, N = 5k + 1 for some integer k (1 goes to monkey, 5k divided equally). Before morning, there were N + k = 6k + 1 coconuts. Working backwards through each sailor's action, if each takes 1/5 after giving 1 to monkey, the pattern emerges. The general solution is 5^6 - 4 = 15625 - 4 = 15621, but the smallest positive solution is 3121.",
    tips: [
      "Work backwards from the final division",
      "Each division leaves a remainder of 1",
      "Set up the recursive relationship",
      "This is a classic Diophantine equation"
    ],
    tags: ["mathematical", "diophantine", "recursive", "coconuts"],
    estimatedTime: 8,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-55",
    question: "The Wolf, Goat, and Cabbage - A farmer must cross a river with a wolf, goat, and cabbage. Boat holds farmer plus one item. Wolf can't be alone with goat, goat can't be alone with cabbage. How to cross?",
    category: "river-crossing",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Solution: 1) Farmer takes goat across. 2) Farmer returns alone. 3) Farmer takes wolf across, brings goat back. 4) Farmer leaves goat, takes cabbage across. 5) Farmer returns alone. 6) Farmer takes goat across. The key is bringing the goat back in step 3 to prevent it from being alone with the cabbage while the wolf is on the other side.",
    tips: [
      "Identify which pairs cannot be left alone",
      "Sometimes you must bring items back",
      "The goat is the most problematic item",
      "Think about safe combinations"
    ],
    tags: ["river-crossing", "constraints", "backtracking", "safety"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-56",
    question: "The Birthday Problem - In a room of 30 people, what's the probability that at least two people share the same birthday?",
    category: "probability",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: Approximately 70.6%. Calculate the complement - probability that all have different birthdays. P(all different) = (365/365) × (364/365) × (363/365) × ... × (336/365) ≈ 0.294. Therefore, P(at least one match) = 1 - 0.294 = 0.706. This is counterintuitive because people think about matching a specific birthday rather than any match among all possible pairs.",
    tips: [
      "Use complement: probability all different",
      "Each additional person must avoid all previous birthdays",
      "With 30 people, there are C(30,2) = 435 possible pairs",
      "The probability grows faster than intuition suggests"
    ],
    tags: ["probability", "birthday", "complement", "counterintuitive"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-57",
    question: "The Socks Drawer - You have 10 red socks and 10 blue socks in a drawer. You pull out socks randomly in the dark. What's the minimum number of socks you need to pull to guarantee a matching pair?",
    category: "probability",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Answer: 3 socks. In the worst case, you pull one red and one blue sock first. The third sock must match one of the first two, guaranteeing a pair. This is an application of the Pigeonhole Principle - with 2 colors and 3 socks, at least one color must have 2 or more socks.",
    tips: [
      "Consider the worst-case scenario",
      "Apply the Pigeonhole Principle",
      "With n categories, need n+1 items to guarantee a match",
      "Think about what 'guarantee' means"
    ],
    tags: ["probability", "pigeonhole", "worst-case", "guarantee"],
    estimatedTime: 2,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-58",
    question: "The Locker Problem - 1000 lockers, all closed. Student 1 opens every locker. Student 2 closes every 2nd locker. Student 3 toggles every 3rd locker, etc. After 1000 students, which lockers are open?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: Lockers 1, 4, 9, 16, 25, ..., 961 (perfect squares up to 1000). Locker n is toggled by student k if k divides n. So locker n is toggled once for each divisor of n. A locker ends up open if toggled an odd number of times. Only perfect squares have an odd number of divisors because divisors usually pair up (d, n/d), except when d = n/d (i.e., n is a perfect square).",
    tips: [
      "This is the same principle as the light switch problem",
      "Count divisors for each locker number",
      "Perfect squares have odd number of divisors",
      "There are 31 perfect squares from 1 to 1000"
    ],
    tags: ["mathematical", "divisors", "perfect-squares", "lockers"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-59",
    question: "The 100 Doors Problem - 100 closed doors in a hallway. Person 1 opens all doors. Person 2 closes every 2nd door. Person 3 toggles every 3rd door. This continues for 100 people. Which doors remain open?",
    category: "mathematical",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Answer: Doors 1, 4, 9, 16, 25, 36, 49, 64, 81, 100 (perfect squares). Door number n is toggled by person k if k divides n. Door n is toggled once for each of its divisors. A door remains open if toggled an odd number of times. Only perfect squares have an odd number of divisors because divisors come in pairs (d, n/d), except when d = √n.",
    tips: [
      "Same mathematical principle as locker/light problems",
      "Focus on counting divisors",
      "Perfect squares are special because √n pairs with itself",
      "10 doors remain open (perfect squares 1-100)"
    ],
    tags: ["mathematical", "divisors", "perfect-squares", "doors"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "puzzle-60",
    question: "The Ant and Triangle - An ant is placed randomly on the perimeter of an equilateral triangle. It walks randomly along the perimeter. What's the probability it reaches its starting vertex before visiting all three vertices?",
    category: "probability",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Answer: 1/3. By symmetry, the ant is equally likely to reach any of the three vertices first. Since there are three vertices and the problem asks for the probability of reaching the starting vertex first, the answer is 1/3. This can be proven rigorously using Markov chains or by noting that the problem has perfect symmetry among the three vertices.",
    tips: [
      "Use symmetry arguments when possible",
      "All three vertices are equally likely to be reached first",
      "The starting position doesn't give any advantage",
      "This can be modeled as a Markov chain"
    ],
    tags: ["probability", "symmetry", "markov-chain", "triangle"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  }
];